spring:
  profiles:
    active:
      - dev
---
spring:
  profiles:
  application:
    name: microservicecloud-config-krystal-dev
---
spring:
  profiles:
  application:
    name: microservicecloud-config-krystal-test
